// Meeting Transcript Chunks - Add these to clipDocuments.js
// Generated: 2026-01-09T09:55:36.247073

export const meetingTranscriptChunks = [
  {
    "id": "meeting2-chunk-1",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 1",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "I got you. I can do you. You're good. Righty. I got you. I got you. You guys in the room. Is it. I got you. Or. I got you. Oh. All right. There you go. Oh. First you want to go to the. Is it agneth or is it agneth? Agneth. Agneth. Agneth. Agneth. Agneth. Agneth. Agneth. Agneth. Agneth. Agneth. Agneth. Yeah. Let's go. Agneth. This is. Susha. Like a sound like Susha. Oh. Yeah. Susha. Yeah. They want to. Did you speak any training or a restaurant? I understand very well. I don't. I'm terrible. I'm speaking. I can't. But not very good. I can't. I can't. I want to. How about German? Oh, no. That's. I'm just. Yeah. Thank you problem. Yeah. Okay. I don't like the German that was nothing. It is the German people. I just don't. Yeah. Are you. Do you think you're not going to stay there? Or much longer? Well, you stayed there longer? I hope not. That's not my dream country if you ask him. No. Neither is no. Okay. Just there. A little that I've seen. I can't do shots of vodka. vodka. Go to Russia. Go to Russia. Go to Bosnia and the Balkan. All right. Just don't. Donald Todd. Welcome to the show. We need to finish the Paul Meadow clip. All right. The only reason I'm not in the room, guys is I'm trying to take notes. Follow along. It's a lot easier with multiple screens. So apologies for not being in there at the moment. You're all good. You. All right. All right. So. Here we are. I'll be back. I'll be back. I have to put on room. It's on you here. So. Go to the team. When back, we map the current credit score. You in the office today, let's get in this room. Yeah. Oh, that's true. I'm sorry. So it's hard. To present from there. Yeah. You mean. So from here, we are looking at the clip limit threshold. So we want to use whatever the clip limit is. So we're just going to use the default. So we can either adjust the formula here or there's a little check box. You can just deactivate that individual formula. So it's not used and it doesn't fail. So in that case, we're just going to use what the default max is. Man, it should be 20,000. So clip, see our limit max, 20,000. All right. So we have a bunch of other thresholds that we have to pay attention to as we work through a clip analysis with a client. We review this information and put in. Now they did not adjust them. These are what our recommendations are and they did not change it. So we need to go with our recommendations. And they also did not adjust the credit ranges at all. They just added that they wanted to adjust them after the fact because we're looking at both credit cards"
  },
  {
    "id": "meeting2-chunk-2",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 2",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "and lines of coverage. But they want to make sure that they do not have a maximum aggregate limit of more than these values in these ranges. So we're going to adjust all of the credit based on this information. And we're going to be able to tell from the output file. What their current credit limit is. What the suggested increases to. And then we need to look at the multiple lines of credit to make sure that they do not go past these values. So bind right can can bind. Yeah, so if there are 776 or higher credit score and say the individual Justin Todd has a credit card of 20,000 and a line of credit of 6,000. That's above the 25 max. So we would have to lower one of the values. So if the line of credit is that 6,000 that means that we would just look at the credit card and move it to 19,000 from a 20 makes sense. Yes, we're thumbs up. Okay, and this is all based on the monthly spend. So this is another attribute that we have to look at. I almost feel like I shouldn't have suggested it now, but you know, it's all good. We'll get it done. So do you suggest this not suggesting that to clients in the future? No, I think it's important because it helps bring the card back to top of all it. So if if my credit card, if I'm not using my credit card because I have a $5,000 limit. And my credit card company receives attributes from the credit bureau that says that I use way more than my $5,000 limit. So that's probably a good indicator of why I'm not using it because my max limit isn't within my monthly spend. So if we can get information that says that Justin uses closer to $10,000 a month on his credit card, then we need to increase the limit from $5,000 to at least $10,000. In order for me as a consumer to even think about using the card. So that'll make sense. Makes sense. And it's pretty, yeah. So it is something we have the data. We can use it there the way that Pometo citizens is requesting. Us to use it is a little bit different than what we've done in the past, but you know, with a little bit of a wishful thinking. We can figure it out and make it happen. So we're going through the parameters. Once we're set up here, we look at the actual groupings and go through this just a bunch of nested of statements. So this doesn't really matter. These are just credit limit groupings. This part doesn't affect anything. So we'll just close it. The change in credit score is just taking the current minus the original. That's it. No income estimate. So if the income equals zero or if it's empty, then one here they are asking for"
  },
  {
    "id": "meeting2-chunk-3",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 3",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "a minimum. So we need to put that in here as well. So income estimate, let's see if we can see where these values are. So 20,000. Let's see if we even have anyone close. So I don't even see anybody in here, but there probably is somebody at some point. So we should add it. What are the numbers represent? So it's in thousands. Okay. 20, 30, 20, 20, 30,000. So here's six right here that have no DTI, no income estimator. Five. No data birth for a couple of them. So we're not receiving any data. So some of these will fall out anyways, but there's a couple of zeroes and then errors. So these guys are going to fall out. But what we would do is we would look at the information. Right all this. You hit the top one there, buddy. Not so. So once I if the income is equal to zero or if it's empty or if the income estimator is less than. 20. Yeah, close the per in there. So. Oh. This one, I guess, because just so less than 20 year empty, but that's what we want to do. We want to add that section. We want to disqualify them. Um, for a FICO less than 650, they have a minimum FICO score of 650. So we're okay there. Make sure a minimum FICO is 650. Yep. Flip threshold 649. DTI is 50 on their spreadsheet. It has 50. It's on my other screen, but I'm validating these values is what I'm doing. Making sure that our parameters are all assigned correctly. Um, the blocks are re-assues less fine. So age has to be greater than 21 and, um, maximum 100, you know, not trying to offend anybody, but we're not trying to give a credit line increase to someone that's 100 or one years old. 99 years old with a different story. Yeah, 99. They have at least two years to rack up the balance there. So we're good. Um, so here, we need to remove this. They wanted three years. We wanted to have a card for at least three. We don't care about that. We want three 65. So they have to have at least the card for one year. And the credit limit. This is just the naming convention. It's not what it actually is. The credit limit max here is 20,000. So that's accurate. If I go drop 50 points is what they're asking for. Nothing greater than 50 points. Um, we don't want anything past do. That's our own logic. We don't want bank rubbed. Well, they added these features. I gotta go find that email now because I don't have it open anymore. And you can do drop that on the fake of drug credit and 50, please. So if we're giving it a one, we're filtering them out. Yes, so if they have a one, you will see that down here. So bankruptcies 24"
  },
  {
    "id": "meeting2-chunk-4",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 4",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "months open trade lines, less than three, month and a half multiple trade lines. So we're going to get you ready. Okay. Okay. I'm having issues finding that email again. Are you able to find it in sentimentally? Top of my inbox. What do you exactly do you need from it? Well, there was in the email itself. There were a couple credit attributes that I said we would use. Oh, here it is. So in addition to customized parameters, we'll review peak monthly spending habits to ensure proposal and efficient confirm that no member has an aggregate limit exceeding 25. Well, they changed it based on color and there's also a few other options. So number of trades 60 days past to. 24 months zero, right? We got that one number of trades 90 or more days past to we've done the link with the link. So we haven't gotten to. This stuff. Number of bankruptcies ever. So we're public bankruptcies 24. So these are like different. I did explain to him that we can't change some of the parameters. He said, what do you say? Thanks. I have a curious. I've got the attributes. Okay. All right. So we'll go back and check those in a second. But we may have to add more here. Because these aren't. These aren't attributes that we're getting. Oh, the ones that he was requesting for this. Yeah, number of trades 90 or more days past to and 24 months. He's saying ever, but that's the trade that we're receiving here. 60 more days past to. I would say for some of these. I mean, we just have to go off of what we got. Yeah. I mean, we told him that we told him that these attributes come from to you. Like these are field names, not like just editable. So. But we don't have anything for any number of trades 90 or more days past to. It would be on one year. There we are. Now, dear more. Okay, so we can do that one in 24 months. Okay. Just into these formulas, they the same as what you use the last time. And need to be adjusted possibly the following time for. Or they go back to like us. And deep or they default to something that's that set up. No, so a lot of these like we found we find to them that these are the types of bars that we we want. These are included in our standard process because we find it to be the best set of users. Or cards that actually use them. So these are the parameters that we set outside of it. I mean, the ones that we allow them to dictate are different lines. Now they don't have to do stuff like this, but you know, we can do it on on our end. We also look at like past do in any line of credit. So like it may not"
  },
  {
    "id": "meeting2-chunk-5",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 5",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "show past do for this particular line of credit. But we're looking if any other lines of credit are past do currently. So maybe this credit card that we're reviewing is not past do, but the member may have a different card or different trade line that is currently past do. So, you know, at that point, it's only a matter of time until this credit card becomes past do so, you know, there's a chance that we don't want to increase their credit line if they're currently past do with with another card or another trade line. So there's just stuff like that that we look at. Reposition trades none and then we come down to the disqualified line. So we want to add the bankrupt seas. They did not ask about the open trade lines and the oldest trade opened one month. And months since oldest trade is less than 24 months. Yeah, then I asked for that. Just didn't. I want to register. Maybe you didn't answer this already, but is there a standard configuration? Um, is there a standard configuration? Yeah, so basically the the standard is only the handful of things that they can adjust. So everything else is considered standard. So these are the parameters that they can adjust and then the buckets for the increases is what they can adjust. I mean, these are just our standard set of parameters. But they're asking for things that are slightly different. So there's fields like the reposition. Excuse me, oldest trade line open trades and bankrupt seas and past do. These are all new that we found work really well to find the right borrowers. That's why they were commented out in the code, but we're adding the bankrupt seas and we're adding the reposition information. Because the client wanted those included. Is there a UI for the client to like, so like these are they done, you know, an collaboration with us. There's not a UI. They're done with us. Or we send them the PDF and then they fill out the information on the PDF because they left this section blank. And we're taking that they wanted our suggested parameters and the same thing with the credit line increases. And this is the only thing that they're changing is they want the current credit limit range based on aggregate limit. So it's the only thing that they had updated in the file. So we're just following that. Okay, so those are made of like a configuration document. Yep. That's how they interact with it. Or they call us right or take it to adjusted. Yeah, I mean, we have a couple like preliminary calls with them and they can do it over the phone, but we try to get an actual document because when stuff's done over the phone, then they'll say we didn't want this update. And it's like, yeah, you did. So that's why we have them fill out the document."
  },
  {
    "id": "meeting2-chunk-6",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 6",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "Yeah, and keep in mind too. This is like, these are one time. Projects, right, so this engagement is we're just running this stuff once. And then we give them the results and if they want to contract us again in the future, they will, which would come with more. You know, another set of potential changes to parameters. What is the the average life cycle of this engagement like from when they. Say we're going to do this till we finally deliver. Well, outside of contracting. It's like two three days. Yeah, and outside of the contract, yeah, contracting a sign like the actual mechanics of it like we get the file, we get the thing we adjust to we and then we return it around. What's the tournament? It's about two three days. Two three days. Mm-hmm. Yeah, it could be inside of that to if. We're just running through it. Obviously, this is taking us a lot longer as we're. You know, trying to capture everything for videos and processes and things like that, but typically we would probably go much quicker through this stuff. And this is a one person kind of like the right the person who initiates the process finish it all the way to the end. Yeah, yeah, really the only. Um, externality would be waiting on transient. There's no handover to any other. Process or person. No, no, just we send off data to trans union. And when we get all that information back, we can pick right back up and keep moving to finish line. Sounds good. Thanks. And then hold on, we discuss this with the client. Or do we do it at the redest class at all. So in this case, I did. Right, this. Basically this engagement came from. Um, doing a MDPA consultation. Okay. So you take that following your perspective. Yeah, so we did a full like loan analysis and then recommended that they do a clip. And then that's why we're here. Thanks. Thank you. Thank you. We have five. We've got to double once a year. I wanted to be. That. You know, because I'm. Contrary to. But it's just wanted to come back. Thank you. Please. Please. Just work. Yeah. Okay. So I have an email where they added. Um. A few new pieces. So they want the bankruptcies in the past 24 months. Um. And reposition trades non-existent. And then they're also looking at the number of chargeoff trades in the past 24 months. They say ever, but we don't have that field. And they say number of trade lines that are more than 60 days past two. And then they also asked for traded lines that are more than 90 days past two. But I'm only adding the 60 days because if um, alone is 90 days past two, then at one point it would have been 60 days past two. So I don't that's three done that. So said to"
  },
  {
    "id": "meeting2-chunk-7",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 7",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "you. Well, here's an example. Hello, now it's 90 days past two. I'm kidding. Well, you find it. You'll be fine. No, but another one. I think it would be very strange if. If it somehow got the 90 days past two with skipping 60 days past two. Exactly. So that's just what I'm saying. Um. Okay. So there we did. We added them as parameters. It's not part of the standard clip process. But I mean, there's we get an absolute boat load of parameters from Trans Union. And you can fine tune it really. How are you see fit? Uh, but I mean, for example, we get four hundred and nineteen fields from Trans Union. So you can just see how they're just forever going. Um, we have that metadata like a dictionary or anything anywhere. Yeah, I want to share a drive. Okay. But there's a lot of really good information. There's also a bunch of information that doesn't make any sense or nothing that we would use for credit cards. Um, but I know that there's other stuff out here that's that's pretty relevant. And there would be, you know, good to possibly enhance the data set at some point. But that's why we're these programs are so successful because we've spent time going through. We've spent time going through the attributes and of cherry pick the ones that are most relevant to see the best results because we've run hundreds of these analysis in the past. Okay. So now after we, um, add these parts, then we ask if they've met the parameters. If they've met the parameters, then they get a one. If they did not meet all the parameters, then they get a zero. And then after that, we are determining the monthly income and the monthly minimum payments. And then we're applying. Um, the proposed new limits, we're adjusting those. So let's do this. Pull this over here. So for the new limits, we want to make sure they should be our standard, but I'm just going to take a quick peek and make sure. So we have less than a thousand. So. Less than a thousand. Move to 1500. 2000 to three. 3 to five. Or to six. Five to 75. Then 75 goes straight to 10. And then we take a minimum of 2,500 plus the limit. Up to. 2000. 20,000. Okay. So that's what we're doing. So basically, I'm just verifying that the formulas for the Kerala and increased program are matching these kind of buckets and these tier. And these tiers. Um, they do. I just had to adjust the first one. And then I just had to adjust the last one to max of 20. Um, where we had 25 in there for before. So now we have a maximum 20,000. And the first bucket is a thousand. So everything looks good. Um, this is a whole another way to do it. Um, but we don't need"
  },
  {
    "id": "meeting2-chunk-8",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 8",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "to get into that because we're not doing that. Doesn't keep do me a favor and just container those like five. Formulas, tools. Just so like I know what I'm looking for when I'm coming in here in the future. Thank you, dude. Um, I'm going to leave you a little trace. Um, I think that's, yeah. I think that's how you're taking. Right. Yeah. Oh, is it all? Uh, you're going to use it all too. And a Christian just kind of like all church wizards. But it's cool. More of a pen ball wizard. Well, I'm just going to go. Thanks for spacing out the, uh, Formulas, just appreciate that. Yeah, I'm, I'm getting excited. Just looking at it. Yeah. I know I don't know my spend as much time in it because I'm going through with you guys. So it's like it's, it's making my eye twitch. Um, so yeah, so that's kind of that. I should be a little bit better. I'll do this. We'll leave that right here because that's in this bucket. And this is another one we're looking at. So here. This is exactly why we add some of the parameters. So here we're looking at loans that have a reposition trade. That's greater than zero in a current credit score. That's above six 49, which is a threshold. And they have 35 records in here. So, you know, there's a chance that these individuals will be dropped for other reasons. But there's 35 extra loans. So the reason why we say we find like the right borrowers is like just because they had a reposition trade at some point in time. Like Paul Metacidicinist doesn't want to have that information. But doesn't mean that they're a bad bar where at today. So that there's a big difference in a 650 credit score that's going up. And a 650 credit score that's coming down. Okay. And you know, Chris can go into that later point. If you guys are truly interested in understanding that. But just because they were, you know, a bad bar were at some point in time. Doesn't mean that it's today. So we would take a deeper look at these 35 loans and see if, you know, I mean, because some of them are in the 700's. Like that's crazy. If you're not going to give someone in the 700's and increase. And unless they're like maxing out the card. So there's just different attributes that we look at. And that's why that's how we find the correct borrowers. All right. Um, so where were we? We were here. We adjusted the parameters 20,000 everything looks good. I want to look at these other pieces. So what we're doing here is we're assigning the debt to income after the proposed new limit. So that's why we were looking at the current monthly income. And we're determining what their monthly payments are. So one of the things that we do"
  },
  {
    "id": "meeting2-chunk-9",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 9",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "most credit cards and your credit card included if you have one, there's a minimum payment threshold. And that's how you determine the minimum balance that you owe. So this is 3% is the minimum payment. Sometimes it's 2%. So that's where the value could possibly change here. So we want to customize it to use to work with their credit cards. If their credit cards is times in the current balance by 2% then we would adjust it to 2% but in this case it's 3. So we're going to leave it at that. Once we assign it then we're basically just saying if they qualify for the new increase and we're assigning a Boolean, we're going to have one or zero to let you know. And then the original proposed new limit values. I don't even know what this is for. Not only remember. Let's get to know. I think we added this because the proposed new limit values. Okay, because I adjusted it so much for the previous run. So this was just the default from the very beginning. I see we're only going to 14 to 50. All right, so yeah, that's that. So that we're not going to work with doesn't matter. So what we're doing is at this point we're deselecting a lot of the fields and we're filtering. So this filter is just saying hey we only want those that qualified so of the 25,000 that joined in only 17,000. 284 qualified now we added a couple of additional fields. So I'm assuming that number will go down a little bit from 17,000. So let's see because we added a couple of extra parameters. No, it went up and then increased. I can't be right. Yeah, I can't be right. And unless they're dollar amounts are higher than what we're in there originally. And it allowed us to expand. So that's true. It did. So that's part of it. All right, we will check and make sure everything still looks good. But basically there's 18 now. So what we want to do is we want to look at the proposed numbers. These are the proposed new limits. So the 1500 means that they had a thousand dollar credit limit or less. So these all have a hundred dollar credit limit. And I'll put them up to a thousand. But we want to make sure that there aren't any. We don't really have any of the fields here. So we need to go further back. Even here the fields aren't coming through. So I need to do quick analysis. Just make sure all this is looking good. Just in the habit of question. Are these credit line increases. Like up in or at the or customers actually just pass them across the board. So this is like this is like if you're just chilling out your house and your credit card company just sends you a letter and says, hey, by the way, you've"
  },
  {
    "id": "meeting2-chunk-10",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 10",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "been a good bar were. You have a five thousand dollar limit. We're going to increase you to 7500. So you're not doing anything yourself as the consumer. So you're not going to have to go to the credit union. These these are automatic. Yeah, so they're they're looked at under the principle purpose of account review. So periodically credit unions and banks and financial institutions are allowed to. Pull your credit just to see you know where you stand and they do this for that for that reason. Now my question is. Does do we do a center right we call it credit line increase. Do we do automatic credit line decreases. We do not. No, would we ever recommend that. Chris and I would not recommend that. It's not it's not good practice. It's not but I used to work for. We actually just like we did. Great of my new cases. We would also give big increases. Yeah, so I mean, we we can go into that on on a separate, you know, call it it's. I agree with Chris is not something that that we would do as best practice. We would find a hundred ways for you to better utilize that information. Then to actually give so in a decrease. But yes, I mean, could we do that? Yes, we could. Some of our clients. Yeah, so one of our clients asked for that. They want to do a management on the increases. Not looking for an increase. They're looking to manage their credit lines. So it was good. Big issue. That was it was it was Paul Meadow that I said a question to. Well, yeah, we we told them that we went do it. We'll give them the information so they can do it as they know that all of the information at their hands, but we're not going to recommend users to do that. So here this one of the parameters. I'm just taking a quick peek and making sure that none of the there's no values that are greater than zero number of charge off trays in the past 24 months. That was one of the. One of the fields. I want to make sure that there's no collection inquiries at all. That was one of the ones. So we'll go to a high number of descending should also be zero. Number of public bankruptcies again should also be zero. So just take in a quick peek at the new parameters that we added. Number of reposition trays also zero. So number of trade line bankruptcy. So here they did have a couple trade line bankruptcies. Some of these just not in the past 24 months. So like this one, for example, had a bankruptcy at some point in time. Let's see, so they've had the card for a couple of years. They have a $8,000 balance proposed to 3,000. They have a 720, 3 and a 25 DTI. So yeah,"
  },
  {
    "id": "meeting2-chunk-11",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 11",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "that's not anything too crazy. I'm still going to pass that alone. Even after the increase, they're only at 25%. So here's the other ones. We want to make sure that none of the trade lines are more past two. Nothing above zero makes sense. And I think there's anything else about to take another quick peek. Repositions, collections, trades. So we did all those. And here's a go. So months since the most credit card delinquency, and months since the most recent delinquency period. So a couple of these guys in the past two to three years had the link one. See, I was just thinking too Justin, the 90 day. Passed two in the past 24 months. It is possible that a 60 day pass do fell off. And we're in like the 24th month. You understand what I'm saying? Yeah. So just make sure that there aren't any in there. Okay. Go ahead and see there's not. But I can imagine that scenario. Okay. Yeah. See what you're saying. But yeah. So we don't have any better 90 days either. So I'm not going to go back and adjust the logic because we just looked and we're good to go. So we'll move past that. But we will include some of these fields. All right. So we're good. We're going to add. It should be everything. Um. To that and come over here. Of course. This thing is so finicky. Um. So the outputs are being logged. Home at a citizens. It's going out there. So it looks good. Come over here. We'll add some fields. We don't normally give them these types of fields. But we're going to do something else. So I want them. I need the credit range. Yeah. So the comparing of a different. Credit line types. We're doing that outside of all of this. Correct. Yep. Okay. Um. Okay. These are at the very end. Okay. Thank you. Thank you. Thank you. Thank you. Thank you. All right. So these are going back out. Um. The important part is we're looking for zeros and these. So we're looking at records. Make sure there's no duplicates. So we want to be zero. Want to be zero. That makes sense. Um. So what we're doing is we're pulling in all the old information. So this is the current analysis that we just ran for Pometo citizens. Um, and a prior workflow. We had the values come through. Here for qualified and all of these were null. Now that we've finished the analysis. We have ones and zeros to let you know that we did not approve Cureline increases for these two, but for these two we did. That's when we did not all of these we did. And so on so on. So we have the information out in the database. And we can write it from that point and then we're also sending the information. So we're saying, hey, about 74% of the"
  },
  {
    "id": "meeting2-chunk-12",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 12",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "cards that we analyze here are receiving. Excuse me. Cureline increases. Or that were recommending them to receive Cureline increase. So come over here. We're just going to save it real quick because we made some changes. And then we need to open the buckets. So we can actually write. So this is a bucket that writes. This is a bucket that writes. And all sound. Any questions? All right. So everything wrote. We're good to go. That's cool. Be a lot cooler if you did. What are you trying to do now? Step by the two. These are lines of credit. Yep. So the client in this particular case as s. That we look at anybody that might be a single member that has both a credit card and a line of credit. And a term in which one we would recommend increasing over the other. They do not want to increase both. That's cool. That's cool. We don't take all the fields all the way across. What fields are you missing? The ones that we built in you can identify half of. So there's multiple credit cards. And then they probably have lines of coverage as well. What would this is the fun part? So there's a count number. Help number to a count number. 1500. We have the low and ideas. So the original balance is good. So this match count numbers. Let's match. I don't know if we're going to do that. So let's match. I don't know if we're going to do that. So let's hope that the same person did not take out two credit cards with the same day. We'll have two credit cards. So we have three credit cards with that. If the customer wants to do a right thing, I don't know. What's this here? Let's start with called coronavirus. just something we can write. We had it. It's already before. I mean, one of the most different things being adjusted in that home. Just as you want to, I didn't go into the office home. You're more asked if that's what we did for shots when others are. I would prefer to take the call quickly. It should only take a few minutes. I would like 15 minutes and get over with. They postpone the call all the time. So if we don't take it, then we may not have it. And this is a cell phone that we're trying to get implemented so we can receive incremental income. Hey, Muffa, would you like to be part of that call and listen in? We're just trying to get him across the finish line. Sorry. I was talking on view. I was going to say, yeah, we can push this next call 15 minutes out. And we can listen to the album. What do you think? Yeah, so we got here when we were done, right? Whatever that call. Okay. Yeah. We'll be out to the general maker. I'm staying here,"
  },
  {
    "id": "meeting2-chunk-13",
    "title": "CLIP Meeting 3 (Oct 30, 2025) - Part 13",
    "category": "Meeting Transcripts",
    "source": "CLIP Meeting 3 (Oct 30, 2025)",
    "content": "but we'll join this is a different call. Okay. Yeah. We have to call in like three minutes. So let me grab it. Sure and call water and then we'll just meet up after that. Okay, guys. All right. Thanks."
  },
  {
    "id": "meeting3-chunk-1",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 1",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "Yeah. I'll just send it to the MRI. You can do whatever you got to do. Sure, it's my. Appreciate it. Thank you. So my old source crashed a little bit ago. So I had to rebuild what we were building yesterday in order to do the aggregate limit. This part was. Is kind of annoying the way that they're asking for it. So I'm just going to walk through how I decided to build it. But this is really just kind of where expertise comes into play when it comes to, you know, funky things that credit unions as for. And just understanding the portfolio loans and taking some creative license. To get in there because there's more than one way to scenicap. But what we were doing is we took the actual output. There's 18,700 and you know, 95. And then we took these are all the individual qualifiers. And what their proposed limits are. And then we had to get information from the originating loan. So we needed information on the category and like the card status unique ID because that information was not carried through. And then Alice is we kept the account number. But we did not keep the unique ID, which is actually the differentiator between the line of credit and a credit card. So just kind of food for thought on that in the future Chris, when you're doing this the clip step two. And you're assigning the values the clip database keeps a field called account number. You may want that to be the true unique identifier at the loan level. Otherwise you're going to do some funky stuff like this that's a pain. All right. So what we're doing here is we've already found our credit union or sorry, we've already found our. Cardholders, we filtered based on the following criteria. We made sure that the limits were assigned as so. And now we're doing this part down here. So we reviewed credit cards and reviewed lines of credit for the institution. What they're now asking is for the individual cards not to have a maximum aggregate above these values. So if just and Todd individual user has a credit card and a line of credit and has a 600. A 600 credit score, then we'll just say 650 because that's the qualifying limit. The on credit score. So say 650 between those two lines of credit. We cannot go above 13,000. So if one card if the credit card was 5,000 and the line of credit was 5,000. And they qualified, then we could only give them up to it $3,000 increase because they're already at 10,000. Does that make sense? Everybody. Yep. Yep. Sorry, we're all muted. And they also want this as another caveat based on the monthly spend. So they have a lot of additional parameters that they're trying to kind of meet here. So I'm going to walk you through kind of what I did. And"
  },
  {
    "id": "meeting3-chunk-2",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 2",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "then we'll finish finish it up because that's not quite finished yet. So basically like I was saying, we need to grab a couple pieces from the originating loan file and join it them to all the qualifiers because this qualifier list is going to have both credit cards lines of credit. On it, there's also some users with multiple credit cards. There's some users with credit card and line of credit. There's some users with multiple lines of credit. And then there's some users with multiple credit cards and multiple lines of credit. So this was fun. This was really fun. This is what I enjoy doing on my weekends. So I think that we can get home. Yeah, no, we're still. It took a lot longer than expected. So we're joining in the records and you know, across the and Chris, this will make more sense to you guys. I know Agnid just try to follow along and I'll explain kind of what's going on as we do it from like a high level. But here we're joining in the attributes between the card holder qualifying file and the legacy source file that we need in. And we have more records joining then we have qualifiers. So what we're doing is we're trying to get the number down to unique level. So we're only getting one actual unique ID at the at the row level. So that's the best we can get having one off. So from there, I create a filter. So the top line filters going for credit cards. The bottom line is going for lines of credit. So it's almost pretty similar split 9,000 to 9,700. And we're just adding another rank system for them. So. Oh, what we're doing here is we're taking the values and we're ranking them. So as you see, we have two account numbers that are the exact same. We have the individual, it's exact same. If you scroll all the way over, they have both a credit card and a line of coverage. But the way that we we decided and by we I mean Chris and John and I agree. They want to rank credit card above the line of credit. And for the increase. So if the members at the aggregate limit already, then we won't do anything. But if they are not, then we increase the credit card over the line of credit. Everybody follow him. So I rank them. So the credit card when there's multiple source key numbers that align with different rows. They will always rank as a credit card above the line of credit. Okay. So what about the people who only have a line of credit? Are they just ranked two? Correct. Okay. Yeah. So like this one right here. Just to line of credit, rank two. So come back here. Just Beverly by herself. Little bit of doing her thing. Uh-huh. So she's just a line of credit. So she's"
  },
  {
    "id": "meeting3-chunk-3",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 3",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "just a two. So the idea here, Chris, is that every single one of these, we proposed an increase to. So what we're doing is we're going back against that and we're going to filter them. So we only increase the ones that we want to increase in those being credit cards in this particular moment. If there are multiple lines of credit, if so in this case like Beverly is going to come through and. She has a. 6500 credit limit and she's not using any of it right now. So we proposed to bring her from 6500 up to 10,000 and her. Um, peak spend is only 1393. So it's not really anywhere close. Um, but we can see that her average credit line on her open trade lines is 13,000 1,33. So it makes sense to at least bring her from 6500 up to 10. And that will be closer. Uh, if the negative limit is what she's seeking to get it more. or hopefully bring that back to top of wallet. So, you know, and this is the problem with lines of credit is obviously, it's not necessarily a way of putting that in top of wallet. Oh yeah, this was a line of credit, sorry. Yes, that is correct. Oh, that is correct. Oh. Okay. So we're going to present them everything. So everything's going to have a proposed new limit. Everything, not necessarily. Okay. So what we did after the ranking, we wanted to find the ones because they are explicit about these and they just gave us their entire portfolio. So after searching, it appears that they already break these values internally. So we're not going to offer lines of credit increases or suggestion lines of increases on these. So their numbers going to go from the 18,000, almost 19,000 records down to like 2,000 records. And they started with 33,000. So out of their entire portfolio, they gave us between lines of credit. We're only going to suggest an increase on about 2,000 lines of credit because they break these parameters. And they go higher than what they're saying should be the max aggregate limit. So we analyzed all the cards. So we're still charging them on 24, 25,000, but our suggested increase is going to be significantly lower. Then what we would normally send to client. Any questions? We can always explain that. Like your parameters limited us dramatically. Yeah, yeah, for real. So so here we are. So basically what I did is I wanted to look at the values. So I wanted to make it back at a single row level. I wanted to sum the proposed limits. I wanted to sum the existing credit limit. And then I wanted to take the credit score that we're at. So this will help us determine if we're staying within the range. And the same with the credit cards. And we could look at it at a loan or a row"
  },
  {
    "id": "meeting3-chunk-4",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 4",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "level. Not a loan, not a row. Remember, remember, little. There we go. That's better at a member level. And we added the aggregate bank card over the last 12 months. And we added, I can catnated both the IDs and the categories. So we know that a credit card and line of coverage. We know that these are just lines of coverage. So these were pretty easy. So just looking at them, all of these people qualified. So just by qualifying in general, they aren't breaking any of the aggregate limits. Because these individuals only have lines of credit. They don't have. And then the same thing for like credit cards. There's individuals that only have a credit card. So they're going to get removed from the data set right away. And because they're well within the range of the credit card. So they're good to go. So from there, we broke them out into categories of those that had a comma. So this is the ones that have multiple lines. So they either have the two lines, or you can see there's credit card, line of coverage line of coverage, line of coverage, credit card line of coverage, you know, credit card line line. So we wanted to look at all of these and see if we're breaking the limits here as well. So I take back what I said originally. So these 10,000 are going to get increases right off the bat because these are all just single lines of credit. Or single credit cards. Just get some water. So, so we're actually going to do about 10, 11, 12. So about 12,000 over the 18, there's going to be four, five, six, seven, about 7,000 that are breaking the limit. So they won't get it. So like I said, the first thing we did is we want to break out all the ones that had the multiple lines of credit. Because those are the only ones that we need to look at the aggregate spend. So these 10,000, 399, we can say right away that they're good to go. We don't have any questions about them. They're within the proposed limits because they just qualified in general. And they only have one line of coverage or credit card. So they automatically qualify. They're good. So there's 10, there's 10,000 here that we're recommending. Yeah, to start. There's 10,000. Yep. There's going to be more, too. But yeah, there's 10,000, 399 immediately off the bat. That qualifier that don't have multiple lines of credit. So we don't have to worry about aggregated limit. So after we did that, I created a formula that is basically doing this. So we're saying that if the credit limit is above 775, which is this top tier and the credit scores both to 75. And the credit limit, the existing credit limit is above 25,000, which is the original that we want to give it a one. And we did the"
  },
  {
    "id": "meeting3-chunk-5",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 5",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "same thing for the other buckets. So basically if their current aggregate limit is at the maximum already, we want to filter them out. So what we did here is filter equals one. The filter equals one for all these guys. So these 4,400 are already at the limit. So we're taking them out. So we're going to remove these 4,400 from the qualifier list. Wait a minute, go back to which card to your formula. Well, aren't you... Aren't you giving a lot of people ones that... I'm just thinking about this. So you're saying if the current credit score is greater than 775 and the sum of the credit limit is greater than 25,000, than they don't qualify. But then you're saying if anybody's above 725 and above 18,000 and they don't qualify. What about the people that are 775 and above 18,000? Because now you're just qualifying them. 775, it's greater than 775. So 775 is the bucket to 18,000. I understand that. So the second tier would be 726 to 775 and 8,000. The top... like for example here, you've got scores. Let's say you have a 776. And you have a limit of 26,000. You've got a 1, right? Yes. Okay. Let's say you're a 776 and you have a $15,000 limit. You're going to get a 1,2 in this formula. Because they're above 0 and they're above 13. So you've removed a ton of people that probably qualify. You're going to get a 1,2 in this formula. Um... Okay, Thanksensina All right. So how should we adjust this? So if you go to your formula, you would have to say if current credit score is less than whatever the bottom of that bucket is and greater than the top of the bucket. It seems like you got to fit them into the bucket. Specifically. So you could either create the buckets, like basically if your score is between this and this, you're in bucket 1, bucket 2, bucket 3, and then you could say if you're in bucket 1 and you're greater than 2500 than 1, if you're in bucket 2 and you're greater than 1800 than 1, right? Like there's multiple ways you could do this, but you have to, they have to be in a bucket. I don't have the buckets in front of me, but what was it? 775 to 775, is that right? That's the middle bucket. So 776 to 850. So it's greater than 775. I think the first one can work. It's the second two that you got about, you have to be the bounded. So like people above those scores with lower limits aren't in there. If score is above 725, 726, and less than 775. And less than 776. Yeah. And the sum is 18,000. Then we also want to exclude it. Yeah, else if credit union is greater than zero. So I think that's the only one. And less than 775. So it'll be the"
  },
  {
    "id": "meeting3-chunk-6",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 6",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "last ones. Yep. So let's do it in 26. Yeah. I got run it again. I'll see you. These numbers change to you. So 500. So we can't sort of. So now we're only disqualifying 1100. 1180. Yeah. That's better. Right? Yeah. So we have 1180 and then. So now we did the buckets, but we'll have to just do it the same way, but adjust it. Or. Post. Now limit. So the first one was removing the people that are already at the max aggregate limit for their lines. So even though we said that they needed increases, we were looking at the individual level. Not not the aggregated. So we're going to walk those back. So here we need to. Can we also like put a formula? Oh, is that what you're doing now? To put a formula in selling why they de-kewed. I can put them on there for that. I was going to make the proposed limit the same as. And I guess that makes more sense because their credit unions will come back and ask something silly like that. So these probably won't deny at that point. So 3584 3587. So these are going off the numbers here. So the proposed limit is greater than. So these guys. Their proposed limit is greater than what it should be at. That's not true, but this one is. So that's at 25. So that'll go away. But these two. So a 7701 would be 18,000. So we'll have to create a formula for that. So these DQs. 1327 coming down. So we'll have to adjust these guys. Well, that's not a DQ reason. Then is it. No. It's called a reason. I don't know. Maybe you want to call it decision. I don't know. I obviously those those guys were still passing them, but we adjusted them, right? I mean, I mean, I just adjusted to pass something like that. I mean, you're adjusted max aggregate level down and makes sense. So here. These are the proposed limits. So you can probably go to the same level. This is greater than. Let's see. Here's the issue is the aggregate limit is higher. So we can't do this. On this level. So we're not to figure out how to. If I can create this. You probably rip the formula from before your filter. So I have max aggregate limit. So we don't want to propose them. Yeah, I would put like in the description of that decision. Just put like DQ at max at age limit. Like DQ above max aggregate limit or something like that. And for the ones that we are going to. You're going to have to like grab the formula that you use before your aggregate filter. And just use that because you're going to create your buckets again, right? At this time. Like if you if you say like a one or two and a three and they can say like if this"
  },
  {
    "id": "meeting3-chunk-7",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 7",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "equals. Well, I guess it'll always be a one. When we're all going to equal one. Because they're already filtered to that. So the proposed new limit would just be. But here's the issue. We got the credit cards. And the lines of credit credit card line of credit. So we're taking those first. It's got the credit card first. So we only need to adjust the top. So it needs to be like a multi line tool. It can't just be in here. So I'm just. So this guy's got to. A credit card in a line of credit right. And I suppose new limit on the credit card is 17.5. 7 to 10. So we can walk that back. Yeah, what we need to do is for anybody that's got two lines. We need to basically subtract the line of credit out of. The aggregate right. Yeah, and give it to the other line right. So like you could probably do that. When there's still, when there were still concatenated together. But you can't because you don't know what the values are. You don't know which is which. If you've got one that has a credit card and an LC, we know we're going to promote the credit card right. Correct, but we don't have both limits. So we'd have to concatenate both credit limits in order to do that. Okay. So because we don't know what what the limit is. So that's why I was thinking like a multi multi row formula tool. To do it. But it's going to be crazy because it's not always going to be two lines. Sometimes there's three lines. So. This is where it gets hairy. Okay. So we're still working on these. These guys. This one was done proposed to limit zero because they're already above the limit. So these guys now we have to adjust it but not here. So we have the decision just in the box. And we got to see how this works. Well, you could pull off a. You could transform come off of there. It like a total. Right. And then. Append it back in. So then you would have the total line. And it's every row. Does that make sense? Do you know what I mean? And I'm making sense. Like if you if you came off of there and then some. Something everything based on account number. Then you could like you could like append back like the total aggregate to every line. That would just do it down there. That's only 2000 records. I want to put all of them. Okay. Here we heard it. Have them broken out. So it's not that unique. Do they count number level? Because that will be unique now. Wait. Are they all there? They're concatenated there already. Yeah. Do you have the sum of the. Crag it. That's the sum that's aggregate right. Yeah. Okay. Ashtay. What I said, you have too many tools"
  },
  {
    "id": "meeting3-chunk-8",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 8",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "on the canvas and the value like what. Just this particular clip more complicated than any others that you have run before. So that's the process. I mean, this is very much the process that you go through. And now this is this is additional steps, but very aggravating additional steps. Yeah, I think this entire part of it is pretty much. And ad hoc requests for extra consideration of parameters. Like this entire workflow that we're looking at here is something we wouldn't normally do. Correct. So 718. This individual is 718. So they're going to get 13,000 max. So they're already at 13 proposed on that. So we need to back out that guy the 1500. Because our current credit limit is here. So when you take in the credit limit in the proposed. Well, what you can do, you take the sum of the credit limit and subtract off. So you take the aggravated max, subtract off the sum of the current credit limit. That gives you the maximum amount you can apply. Right. So 115. So we have something there that tells you what the max is right. Right. Let me. Some credit limit. Well, I got an ice credit limit. Wait. I'm confused. So what do we have? Yeah, you're going to need that. All right. So we want to take the proposed limit minus the credit limit. We need to know what the, you need to know what the max available is for the line. Why did this change? Why would it? So you, you need to take, you need to take the maximum. That's allowed for their bucket. Do we have that in here? Something's telling us it's over the, the total amount. So do we have, that's not in here. Does it, because it's, it's only in a formula above the kind of breaks it down. Like, what we're going to need to do is have a formula that says, like, if your credit score is between here and here, then max this, if your credit score is between here and here, then max that. And then once you can have the max per row, you can take the maximum minus their current credit limit. And then the C. What's the maximum, you can do to take it to that max bucket. Makes sense? No. So hold on 13. 13 is the max for this guy in this case. That's the max, that's the max proposed. That's the max that he can get proposed. Yeah. So we want to walk out his other bucket. So the proposed, the sum of the proposed, because they're both getting it. So we don't want to do that. We want to do the proposed new credit limit. Well, hang on a second. Wouldn't we only pick the top one anyway in this scenario? And give the money to the top one. Well, you can't, you can't give him 14. Five. Can you? You can, you can"
  },
  {
    "id": "meeting3-chunk-9",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 9",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "inflate above the 13. But that's what I'm saying. Like he gets 13, which is the max for the credit card. So we don't want to give the 1500 on the second line. So I think that for anybody that's in this bucket that has an LC and a, if they have credit card in an LC, just go ahead and back out the LC's all together. Right? Let's see, that's just an LC right there. Right. So essentially, 826, Kraylin at 5000. Oh, there's two of them. There's two LC's. No. Hold on. Why did that credit card not? Right. Good. Good. Good. The rest of the order. Dear bro. Um. Can you join back in the, um. The concatenated products. So you know. Then you could say like if category contains a comma. And all of them can tannic on them. No, no. Every single one of them can tannic on them. Oh, you have them there, right? Yeah. So if you could say some of them have two commas. Right. But the data beyond that loses that concatenated category doesn't it? Yeah, I can add this. So every single one of them in here has a credit card. And line a coverage or credit card and two lines of coverage. Okay. Or here. This one has two lines of coverage. Okay. I think what you need to do is filter it out. So if concatenated category has CC. We're going to go one way and if it does not have CC, that means it's multiple lines of coverage. So I think you're going to have some different way ways of filtering this stuff right because. One, if they've got a credit card and line a coverage, we're going with credit card. If they've got two lines of coverage, now we got to go look at which one we want to adjust. So if the concatenated category has CC in it, we'll go true. So if contains concatenated category CC or contains concatenated category CC. So if contains concatenated category CC, concatenated category CC. So all those ones that are going to go true. You guys are too a clock already. So we're going to have to rejoin again. Reoclock. So all the credit card ones we would promote the credit card. And just take all the ones that are LC and take them to zero. Right. And what are the other scenarios there that they have multiple credit cards? Now here they're not that they have multiple. Are there any words like CCCC? No. Okay. So yeah, so everybody that is an LC in this bucket, the LC, would have a decision that adjusted down due to multiple products. Or just a zero. Just de-cute for multiple product or something like that. But just the LC ones. Okay. If your decision would be if category equals LC, then proposed line zero. Right. Okay. Okay. Okay. Yeah. Because the proposed new limit on the credit card is the"
  },
  {
    "id": "meeting3-chunk-10",
    "title": "Finish CLIP Session 1 (Oct 31, 2025) - Part 10",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 1 (Oct 31, 2025)",
    "content": "maximum, no matter what. It's not like you can shift the money from one to the other right. I don't know. That's what I was going to. That's what I was about to say because here they're saying a max aggregate. But here they've already bucketed the maximum as these. So we're not taking that additional money and just lump it on to the credit card. So that's what I would say. Yeah. Like look, you gave these parameters. No matter what. We're not taking if you had a line of code. Yeah. So if we have a line of credit that we're not taking from the line of credit to apply that additional $2,000 to the maximum. Okay. Of the credit card. Okay. Yeah. We can. No, no, no, no, no, I don't think we should. I think that's it. I think that's it. So if they have a line of credit. We're promoting the credit card over the line of credit. So we're bad. Anybody that's got a credit card in a line of credit. We've. They can then other stuff out. I think we need to jump to this other meeting. Okay. I'll jump on over there and let them know that you guys are coming. Okay. Thank you. No wrong. So decisions categories on credit. Then. So it's already saying adjusted max aggregate limit down. So that's not correct. Right. We have to change the decision. The category equals LC. Then. Then. Then. Adjust say. No, say say. D. D. Cude. Or. Like this. Disqualified line or something like that. D. D. D. Cude. DQ DQ DQ DQ D line. To promote. DQ line of credit. No. I don't want to say this. How about DQ multiple. Product or something like that. That's fine. DQ line of credit for credit card. That's fine. It's explainable. Let me overthink this. So then. But that means the other credit cards are going to say adjusted max aggregate limit down, which isn't the case. No, I could just I think we need to change that decision to say something like. So if categories, then TQ line. L. Discussion. Look. What we. What do we got safer approved. Like a. Recommended increase or something like that. Recommended increase or like, what do we say, and for the ones that were. We don't say anything because the file is recommended increases. So if line of credit, then DQ line of credit for credit card. I'm not going to be these guys wait on a hop over to this other call. It's already been seven minutes. Okay. I'm calm. All right, Agni. We'll probably meet after this if you're still interested. Yeah. We have three. Okay. Yeah. I have a three o'clock, but I'll join you if I can. Okay. Thank you. Bye. Bye. Bye. Thanks for recording. Thank you. Bye. That's recording."
  },
  {
    "id": "meeting4-chunk-1",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 1",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "Grab that beer on the way back. Don't let me. We come back you to say, I'll lay out to these calls, or forever, Agna. Do you want you done? I'm so happy. I'm so happy. I'm so happy. So, yeah, I don't know, I have a couple nice weeks all. We'll enjoy just being whatever outside of work. I'm just being whatever outside of work. What's going to be a show weekend, so we'll start there. We'll start there. Got a baseball game tomorrow, and have a bunch of little kiddos trick or treat him tonight. I don't know. I don't typically give candy away or anything, but sometimes we'll go to the neighbor, so she's just hanging out with him, whatever. There you go. If I will or not tonight, I just kind of feel like we got home and I do my own thing. Hey, there's nothing wrong with that. Oh, no. There's a number of some Halloween evenings that have to really warm just because running round all sweaty and today is not going to be like that. Yeah, yeah, it's going to be nice and chilly. I am back. Guess I was back again. Not Christopher. Okay. Are you sharing anything? No. No. I'll wait. Okay. All right, champ. So we decided that the first time we were going to be here, the first bucket where all straight proposals, because these are all one credit card or one line of coverage. But that is, that is the decision we're saying is proposed line. So these are the ones that I have straight proposed limits. So yeah, I just to propose line in, because this is what we're using over here. So we're saying that if it was a line of coverage, that would be just a small slide. But the credit cards are getting proposed line. Because these are all the ones that have multiple lines. And these are the ones that are just straight yessies. So we're good there. And then these are the ones that with the DQ was above the max aggregate limit. Okay. the false off of those non credit card ones down below right yeah so here we have the 25 49 which is the last last of the moheakens that were looking at and there's like 22 of that false at the bottom oh so for these we got to figure out which is our double lines mm-hmm they look like identical to like yeah some of them have a balance some of them don't they're very very similar 45 49 I don't know I mean we can take it as a day so for for these don't we just want to we want to just take one of whatever their lines are right yeah okay let's see we have we have two here and we're saying that they both get an increase so coming from 45 49 100 so a 35 so we do this why don't we"
  },
  {
    "id": "meeting4-chunk-2",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 2",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "sort them by their highest current limit to sort them by account number and highest credit limit uh this makes sense and then just increase the the higher line yeah so I mean that's what I was thinking but like there's there's just weird cases where you know they have balances on both one of them has a high balance one of them doesn't have a high balance so this one's proposed to go to 10 they have a current balance of five on the six where they have a balance of 276 on 42 100 so and it's both for the same person I mean do we want to these ones they both have all of this ones almost maxed out yeah like I don't this is gonna be a question for the credit union right yeah I mean we can bucket them as like here here's yeah here's like a review 22 we don't know how you want to handle it and we didn't go this in depth but um they all have lines of coverage and we don't want to increase them what we're seeing here is that all of these would qualify as a standalone on a you know case by case basis but they have multiple lines and in case of this one they're both almost maxed out at what the line of coverage is but the attributes credit credit credit credit credit credit credit can't ever take me out of it and but everything else looks good otherwise so you know and this average is significantly higher he has a lot of money he rotates on the bun on them so yeah these are weird I mean on one hand I'm like hey here's more money to rotate around on here I'll earn interest off of you on the other hand I'm like you look like your risky is how yeah but I mean that's that's that's the case though curse like we that's that's why we get such good returns especially when it comes to the you know interchange and interesting come because we we look at lines and if they have a 6,000 dollar limit we find the right borrowers even make be rotating 5,500 but it could also just be like a snapshot time you know what I mean like you can carry like a hundred dollar balance for 11 months but this one month he had to max out his his line because I don't know something at home happened so it's always it's always one of those kind of snapshots but I mean everything else in the line looks looks good so I say Sally can get it. Carp one yeah I guess what we could do here is just have these come off as like you for do put it lines of credit or review as decision I don't know I mean all of this stuff needs to be reviewed the question is how do we want to"
  },
  {
    "id": "meeting4-chunk-3",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 3",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "put these decision comments okay then the day they're not going to get upset the 22 loans we said you make the decision and then and we could even take a step further and be like what did you review additionally what would you like us to do in the future for this and we'll we'll just take care of it so but we wanted to get you the data before the deadline so okay so there's that one that's gonna be yep so into the union what's the last bucket it was the ones off of the proposed that are not hitting their limits so they have an aggregate limit and they're going to 9000 and they are not hitting their limits so let's just do the scosore descending see yeah so they're all maxing at 25 their current is 20 they're going to 25 but these are all 800 scores so we're okay so they're not hitting their limits as in these basically all qualify yeah these are aggregates like the double to a more line set or have aggregate but the aggregate limit of all the proposed lines is still below the 25000 okay so these then we would still say credit cards there ago line of credits or for going for credit card so 24 794 so 7776 so yeah looks like they're all they're all good to go okay so same thing here we're gonna break them out to there are all 800's and 700's high 7's and all of their in both lines are in here and yeah these are all credit cards aligned and then there's one here that's three lines okay so these are going to be broken back out again into individual rows or correct yeah okay yeah but look so he's at 850 credit score he's got three different lines and we can come over here and just look real quick and we can look at all three lines proposed still below 25 I just want to make sure all three those all three of those lines are in that bucket right and we didn't decision any of these other loans anywhere else to me they're all in here right no these are all in here okay well a lot of them only have a single unique ID they have three oh are they all broken out so they all all there okay yeah just the 24 is the max limit but these are the three different lines seeing they're all the same account number but these are the three unique IDs so it's a credit card line of coverage line of coverage a couple of your copy and doubt yes so for these we want to say if concatenated category as CC all right they all have CC uh every single I mean I don't know so there's CC and CC so we're adjusting both and then there's CC CC LC so we could see like what they are"
  },
  {
    "id": "meeting4-chunk-4",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 4",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "but yeah it looks like every single one of them has at least nope looks like we have a lot more of these LC LCs down here yeah we're just fine just all of them have credit cards and then here they stop and they get lines of coverage lines of coverage but even on both lines of coverage they're both under the threshold for the credit score they have so we're just saying to approve multiple lines of credit with increases they never said that they didn't want yeah they did they said they only want one line chosen the only one line chosen that's my that was my interpretation of everything which is why there's the 22 below are down there for review for which one so the other ones were credit cards so here we would have to do the same thing so here you're saying to blanket the credit cards and disinvalde the others well here's the thing we're going to have to because there's some that multiple credit cards right so we're going to have the decision those where it's just CC comma LC we can break them out basically say we're picking the credit card over the line of credit and then for we're going to have to come up with other scenarios I think basically any of them where they have a CC right where making that same decision that the LC row is going to be what's with the blank until I get in bro hey I want to join that last meeting your mart and mothwock asked me to like add them to all meetings we do so I guess I'll just forward them then right to this one so give you a heads up thank you yeah don't run so these we have to review too okay I didn't will you ever complicated now CC LC CC LC And LCLC, we have to figure out. Right, but those that are CCLC and CCLC, all the LCs we are going to disqualify in favor of the CC. Correct? Yeah. Okay. So for this filter, you can have a decision. Okay. So I'm going to... I'll try to figure out what to do. Okay. Okay. So I'm going to... I'll try to figure out what to do. Okay. Okay. Metadata. So... I'm going to... I'm going to... I'll try to figure it out. I'll try to figure it out. So that's good. But yeah. So here. So all if category... Do not have LCLC. Well, that was category. Oh, it into the... Oh, yeah. I'm going to do that first. Of course. You got to break out the categories. This is mind-bending. Yeah, that first beer is going to be great tonight. I'll tell you that. Yeah. So I said this is so annoying. Okay. Alright. So now that we have these back, we're ranking them... If category is... LCLC... And zero. Okay. Proposed line. LCLC. Sato. So that worked. Beautiful. Okay."
  },
  {
    "id": "meeting4-chunk-5",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 5",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "So now we're going to come off that false. So yeah. Now we've got this big beauty. So these are just LCLC's. LCLC's again. So we should buff it. So we should buff it. Yeah. CCC isn't here too. Oh yeah. But I'm saying we should take the LCLC's and bucket them down here. Yeah, you're right. With these because it's the same damn thing. Yep. So we actually have more. Yeah, if there's like 240 of them in need review. Yeah. But it's just the LCLC's right. Where do you want to send the CCC's down there too? I hold on. I just put 10 there wrong place. Yeah. Well that's right. So we're taking. Yeah. So we're taking out the proposed limit. I don't think I meant to do that. No. So we're still leaving the limits for them. Down there we are. Yeah. Why did I even, we don't need this? What's well. So here we need to remove. And we need to do two filters off that. So we're going to do a filter and a filter. But this is the filter to the filter. Why are you, why are you having another filter come off of there? It's the wrong location. No. To. Just make sure you're paying attention. The trace bus the bus the filter. Okay. So let me to this 283. So the CC's. So these we just want to disembow the LCs but we'll. We'll do that second. So we need. LC. I don't know. There more. So now I just the LCLC is we need to move. So. Oh, I'll see. If we can get category of LCLC. We can get category equals LCLC. And we get the trace bus the bus the. Yeah, you can go through sort of that union down there. Yeah, but I can't go right into the union. Oh, it's got to go through the thingy. It's got to go through the thingy. And you. So why did I add this? Why did we add what the union there? Or the filter. So I end up filter. The cathilp the fish. Can you. I'm so confused. Yeah, it's pretty cool. What happened was. It's too ridiculous. I. It was. Two, seventy. Sexy. I don't know where they're. Oh, two, eighty. See, on the majority of these are LCLCs. So we're going to go. We got to go back to the LCLC land, you know. P. Now, I'll go filter. Now I'll go filter. So these are going to go here because these are the same things. These are all. LCLCs union at before the. Oh, we the reason we had that sort there was to like promote the. Right. Yeah, we were just looking at the lines. We don't want to end up doing anything with it. Yeah, because there. So I'm just going to bring it over here. But it's the same thing. Well, here we are with the dang zeros again. Well, I, I,"
  },
  {
    "id": "meeting4-chunk-6",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 6",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "I turned it off so we're not doing this. That's fine. All right. So the data's coming through. No records. I know John. Can't connect on a con cat. You're, you connected on the con cat. Um. You need to go to. And cat. In the. Not just on my wills. What's the unique idea those guys? Yeah. It seems like there's like. What the world. So it only exists where where's the other stuff coming from. Like going from here. Same pipeline. Yeah. That's where you're. 3500. 4000. I'm just going up there unique idea somewhere. No. Oh, look at me. I'm here. Oh, look at me. I'm here too. Okay. They all, we go down. They're all sitting there on the right. There's nothing there. There's nothing from anywhere. There's nothing from anywhere. There's nothing there. There's nothing from anywhere. Do we do that process? We didn't run it. I need to go home. That's like that. Check. Oh, my. Yeah. Good. Yeah. I need to go home. I'm 76, 86, 96. We all just sit there. Won't you speak up? Jesus. Yeah. I'm really proud. Well, I was thinking that you're just validating it from the code and everything as well. All right. Yeah. This is just ridiculous. Normally you don't have to do this. This is just so kinds or ridiculous. But now we're here to. We're down to seven loans, guys. Seven loans. Can you do this? I'll be like, no. No. No. Can I? This is way more in depth than what we normally do for a clip. Oh, God. So I'm never going to remember what's what. Oh, God. Yeah. Yeah. That's good. So there's other lines of credit down there. Yeah. So there's going to be two lines of. Well, one line of credit. One line of credit. So it's just this guy. So we can just slap. We can just slap. See. Yes. So if category is Lc. And DQ. Four credit card. And then. Well, we're going to do these credit cards. They look identical. It's weird. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. So. Well, so. limit, so just sort them by the limits. Take it to the limit. I mean, like also, if we had more information, it might help us, like, you know, and I can tell all of this is like, I don't know if you've got a rewards card that you might wanna increase the limit over the non-reward card, right? Like, anything to try and get people to use cards more. Yeah. Usually rewards card has been used more, right? Yeah, yeah. Because once the increase recently happened to me also, like the increase in the annual fee, initially they said, no fee, then they started. After so many years they started. Oh, you're using it, so we'll increase it. And pay some fee for"
  },
  {
    "id": "meeting4-chunk-7",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 7",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "that for extra credits or extra rewards. And then you can just add that to the card. That's one has three. Oh, but this is the line of coverage though. No, this is the line of coverage. It's line of credit. Yes, that's what I said. Line of credit. Okay. Yeah. Okay. Yeah. All right, so... Well, we're gonna have to do it centrally. So we want to take the credit and we're going to zero it. And then just take the first value. So it's gonna be you. You. And do we want to say multiple credit cards or review? Because there's only like three accounts here to me reviewing. All right, so just take out of our hands. So take the LC make it a zero because that follows the other logic. DQ line of credit for credit card L. Credit card for multiple credit card for review or something like that. Do duplicate credit card for review? Okay. Do duplicate. Do duplicate. Arriba. All right, so that she was a total. With everybody decision right. What do you like to know? 18, 796, 18, 796. There she believes. Beautiful. Give me this thing. Now, I'm gonna just send an nickname. Filter right. Who am I? She's always who's getting all these dang fields. Okay. Okay. Are these fields coming from? What? Left and right, so they're gonna have to be coming from unions. So go look at your joint. Just did. Aggregate spend over 12 months. So we'll give them the category. The unique idea. Decision. And remove the other stuff. So that should be everything. Because here we have 31, 27, so it's you. It's you. You know what happens to it in there. So everything looks okay. TTS. It's the critical month decision. Decision. Decision now. So we have five values proposed line. Decude line accredited for credit card. Decude above max aggregate. Dependent line coverage. And Decude line up. Dependent credit card for review. Decude. But max. And then. Dependent. I'll see for review. You click it. C.C. Or review. All right. Those are the five. Decude line accredited. That'll just change to. Share members. Five. Four. Craven. Yeah. Or a winner. If just can. Come. Yeah. Pride. Our next one is. Or. Jahahaha. And just. Okay. There we go again. Again make one small change you got to make it forever time What did you change? Change it from DQD to DQ line of credit. Oh To make it consistent so now yeah credit so we have duplicate credit card for review duplicate line of credit for review 298 there's a lot of those DQ above max aggregate In the case of credit that we do not recommend And increase on in favor of in Resign credit card Scallacks in increase of e Team? Yeah... I'm out. I'm out. I'm out. Oh. Oh, those. That's all it do. I'm just putting it right here. zur\u00fcck I get to the limit. Buenos Aires 1-0"
  },
  {
    "id": "meeting4-chunk-8",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 8",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "B pistol I llame All right, so we have the full 14. I'm going to go to this. So I want to go. So all these guys in Sarah, DQ to buff max aggregate limit. So that's pretty cool. Be lacku-licked it. So that's the 0's here. So at this point, right, we would have him review the output and tell us, which if there's anything that they have a different opinion on or what? No, I wouldn't ask for that. I mean, we can have them share the logic for these, but we didn't get enough information. I mean, if you want to go back and they say, oh, yeah, we would take the one with the higher limit, we would take the older line of credit or whatever, then we can implement that into the workflow. And then what I would do is just, I would write a little note down here, you know, just add a little comment box that says something along those lines. Well, I think at this point, like I mean, we just decision everything we could based off of the information they gave us. The only thing that I would want information back on is like what they actually increased lines on, right, because when we're doing analysis next time for them, like full loan grading, we want to be able to give them as much information out, you know, insights on the performance of these line increases that we can. Right, yeah. Yep, so that makes sense and we have the file here, so I can link it to you and you can give it a send. So it is the file that's the qualifying file, don't send them the one that says to you on it. By the way, the qualifying one. Okay. Yeah. So that is there. This is here and that's the show folks. So this one was more of a pain, the reason for that and why we had to create all of this is because the credit union gave us some additional information. And basically, they wanted us to take into account normally our normal process, which is, you know, almost fully automated is doing a sign parameters like this, which are really easy to fix or change. And the signing parameters like this, that again, are very simple to adjust and change. It takes a little bit of manual work, but they wanted to do something slightly different. So instead of saying, hey, anyone that meets this criteria up here gets an increase and that means if Justin has two credit cards and he meets the criteria here. And then he could technically get an increase on both of those credit cards. They wanted us to review their lines of credit and they wanted us to review their credit cards and that we ran into situations where not only do they have a credit card. They may have two credit cards and then a line of"
  },
  {
    "id": "meeting4-chunk-9",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 9",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "credit or multiple lines of credit and a credit card or just multiple lines of credit. There's a lot of different scenarios and when they assign a max aggregate limit across all of their lines of coverage at a member level. Then it gets a little more complicated, but then to further complicate that. They also introduced credit tiers. So now there's a max aggregate limit of just not a flat 25 for anybody that qualified. Now it's broken out by credit tier. So that's another level. And then is if that's not enough, they wanted to break it out by the monthly spend to look at the monthly aggregate spend that we're at least meeting the minimum on on that. So it became a bigger project than originally anticipated. So normally in analysis like this would probably take start to finish maybe three or four hours. I would say it's probably taking about eight hours now. We today are really going to look for like in the manga. Say what? No, which data in the work flow will do that analysis is it your depth? Where do we get the information? The data which you said eight hours right. So it has two process the data. Yeah, so they sent us a data file. Oh, we. Yeah, so this was the data file that they sent us and we reviewed it and we ran it through our workflows got it cleansed for trans union got it back from trans union and then re viewed the information. And then we had to get in our database. We had we had to append some additional fields that we're missing. So we had to add them. And then we had to do a bunch of scrubbing and ranking and a bunch of different work as well on everything before we can create an output and then we have different decisions that we came up with at the very end of the day. And then we just gave them this file. So the 18,796 records were all those that qualified for a line increase based on our normal clip process. But because they introduced new parameters like this. We had to kind of work on the fly and adjust those and then doing so. 13,843 records still received proposed line increases as is. 3400 we disqualified the line of credit for credit card. So this means that the member had both a credit card and a line of credit and the institution said that they wanted to give. I'm sorry, they left it up to us to determine. So we made the decision to give the credit line increase to the credit card not to the line of credit. And then these loans about 1100 of them words is qualified because they're above the max aggregate limit. So we're seeing the 13,834 lines. We are saying increase those increase. Yes. Yeah. I didn't realize the volume was that high. Yeah, we would have"
  },
  {
    "id": "meeting4-chunk-10",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 10",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "increased 18,000 plus loans based on we started with 33,000. Keep that in mind. Got you. Got you. So yeah, we're still saying 13,000 should get increased. Whether it's a credit card or a line of credit. And then there's some duplicates that we did not clarify with them beforehand. So these six duplicates for review or credit cards. And by duplicate, it's not it's not really a duplicate. It's like Justin Todd has two credit cards. One has a $5,000 limit. The other one has a $6,000 limit. But based on the attributes, both of them qualify for a proposed limit increase. We didn't get information from the credit union on how to determine which of those two lines should receive the increase. So whether they go off the oldest card, whether they go off the highest balance, the highest credit limit. We didn't clarify that information. So I'm fine, given it back to them. If they wanted to, these lines still qualify for these are all lines that we say qualify anyways. So it's fine just to give them the increase on all of them. But we added a decision field that we never do when we do this type of analysis and we're sending it out to them. We will say, kind of what happens there. And final decision for those 13.000 is solely by the credit union right, whether they want to increase or not. Those 13.000, the first line proposed or line increase. They will take the decision to increase or not. So it's always their decision. So we give them this field proposed limit increase. And we always allow them to choose. This is just what we suggest that they increase to. But they can adjust it as they see fit because they're their members and they may know Donna better than we do. We're looking at the data, which gives a pretty holistic view, but they may know their individual members better and maybe they decide that they don't want to give a $19,000. Okay. Limit. Yes. Okay. So I don't like this. Well, it's been delivered to Nick. So. But to me, you don't like it. I don't like this. This is above the max limit right here for. That's two people. Sorry. Look, it's the same person. Nancy Hughes, it's above the max limit. There's one credit card and two lines of coverage. And we de-cute all of them for being above the max aggregate limit. But if you take out the credit card. We could have given the increase to the credit card. It doesn't matter. They don't want them to have above the max aggregate of the amount. All right. Oh, their current is above the max aggregate amount. Yeah. Okay. We're good. I got stopped looking at this. I'm going to find all kinds of stuff. All right. So that's fine. They're joined. We're Gucci. And that's it. Any other questions, guys? No, just a thanks film. Thank"
  },
  {
    "id": "meeting4-chunk-11",
    "title": "Finish CLIP Session 2 (Oct 31, 2025) - Part 11",
    "category": "Meeting Transcripts",
    "source": "Finish CLIP Session 2 (Oct 31, 2025)",
    "content": "you. I don't know. I don't know. I'm thinking of any AP. I don't know if we need to schedule anything for that. Looks reasonable. Yeah. I mean, we're not going through the. We don't have one. Yeah. We don't have one to to go through. But. Yeah. Yeah. We can we can run through the high level process. And I can you know, pretend that we're going through it. But we're not going to be able to get as in depth on something like this with it. So. But yeah. Yeah. We can we can do something along this lens. We've been working on a two-pound schedule. So. A lot of Sweden. They have as lookingspring dogs. Hi. Playing it for the next week. Hi. Everybody to take these pictures."
  }
];
